apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      containers:
      - name: beat
        image: mayan05/dtq-app:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "app.worker", "beat", "--loglevel=info", "--schedule=/tmp/celerybeat-schedule"]
        envFrom:
        - configMapRef:
            name: dtq-config
