apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: mayan05/dtq-app:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "app.worker", "worker", "--loglevel=info", "--queues=default,low"]
        envFrom:
        - configMapRef:
            name: dtq-config
